    on: push
    jobs:
        build-container:
            name: Build container
            runs-on: ubuntu-latest

            steps:
              - name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
           
              - name: Build and push
                uses: docker/build-push-action@v3
                with:
                  push: true
                  image: ./Dockerfile
                  tags: ghcr.io/vincy/hello_react:latest
 
#            steps:
#            - name: Checkout code
 
#              uses: actions/checkout@v3
 
#            - name: Login to Docker Hub

#              uses: docker/login-action@v1

#              with:

#               username : ${{secrets.DOCKER_USER}}
#               password : ${{secrets.DOCKER_PASSWORD}}
                

#            - name: Build and push to Docker Hub

#              uses: docker/build-push-action@v2

#              with:

#                 context: .

#                 push: true

#                 tags: prajwal1718/v_react_app:latest 
                 




# name: Docker Image CI

# on:
#  push:
#    branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

#jobs:

#  build:

#    runs-on: ubuntu-latest  

 # steps:
   # - uses: actions/checkout@v3
  #  - name: docker login
   #   env:
    #     DOCKER_USER: ${{secrets.DOCKER_USER}}
     #    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #run: |
       #    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         
    
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag prajwal1718/v_react_app:latest 
   
   # - name: Docker image tag
   #   run: docker tag vreact_app prajwal1718/vin_react_app:latest
 # run: docker tag vreact_app:$(date +%s) vin_react_app:$(date +%s)
      
#    - name: Docker Push
  #    run: docker push ${{secrets.DOCKER_USER}}/prajwal1718/v_react_app
           

