name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
         DOCKER_USER: ${{secrets.DOCKER_USER}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag prajwal1718/v_react_app:latest .
   
   # - name: Docker image tag
   #   run: docker tag vreact_app prajwal1718/vin_react_app:latest
 # run: docker tag vreact_app:$(date +%s) vin_react_app:$(date +%s)
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/prajwal1718/v_react_app:latest
           

